# Generated by Django 3.0.5 on 2020-05-21 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory', models.CharField(default='', max_length=100)),
                ('price_month', models.IntegerField(default=0)),
                ('price_year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTopic',
            fields=[
                ('vt_id', models.AutoField(primary_key=True, serialize=False)),
                ('vt_img', models.ImageField(upload_to='images/')),
                ('vt_desc', models.CharField(default='', max_length=200)),
                ('inMembership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkernel.Membership')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('vc_id', models.AutoField(primary_key=True, serialize=False)),
                ('vc_desc', models.CharField(default='', max_length=200)),
                ('vc_video', models.FileField(upload_to='videos/')),
                ('video_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkernel.VideoTopic')),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_phone', models.CharField(default='', max_length=10)),
                ('Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkernel.Membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
