# Generated by Django 3.0.5 on 2020-05-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkernel', '0003_auto_20200522_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vkernel.Membership'),
        ),
    ]
