# Generated by Django 3.0.5 on 2020-05-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkernel', '0004_auto_20200522_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='vc_video',
            field=models.CharField(default='', max_length=500),
        ),
    ]
